### ISSUE TITLE
Deployment documentation needs finalized

### ISSUE THREAD

**Issue by jharmison-redhat** [RedHatGov/devsecops-workshop-code#2]
* We should have a guide for facilitators on how to build the workshop for delivery.
* This guide should include basic setup, customization, and some troubleshooting.

**Comment by andykrohg** [comment]
This thought just occurred to me the other day. I was thinking that even with all the documentation in the `README.md` and `*.example.yml` files, there are still too many knobs for a newcomer to turn to enable easy adoption. I propose we create something like an "RHPDS Quickstart" that goes a little something like this:
0. Observe the opinionated defaults in `/vars/rhpds/common.yml` and `/vars/rhpds/devsecops.yml` (already created)
1. Order OpenShift 4.5 Workshop on RHPDS (select Let's Encrypt = true)
2. Install `docker|podman`
3. Add your RHPDS `guid` to `/vars/rhpds/common.yaml`
4. Add your `reg_rhio_pull_token` to `/vars/rhpds/devsecops.yml`
5. `oc login <RHPDS>`
6. `./run-container.sh -k ~/.kube/config -c rhpds devsecops`

**Comment by jharmison-redhat** [comment]
Could also create a small helper script to prompt for unset variables and walk through a small decision tree. Wouldn't take me long but it's just another thing to debug when things break :upside_down_face:
